# -*- coding: utf-8 -*-
"""python_fundamentals_español.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMx--0h9q4nE2G4sRX-78mb76nzSQl_G

# level 1

## define una **lista**...
"""

cosas = ['carro', 'zapato', 'cuaderno', 'cuarentaYcinco']

print(cosas)

"""## recorre lista con **"for loop"**
El bucle **for** se utiliza para recorrer los elementos de un objeto iterable (lista, tupla, conjunto, diccionario, …)
"""

for x in cosas:
  print(x)

cosas_copy = []
for x in cosas:
  cosas_copy.append(x)

print(cosas_copy)

"""## ahora con '**list comprehension**' embes de 'for loop'..."""

cosas_copy_v2 = [x for x in cosas]
print(cosas_copy_v2)

"""list comprehension pero modificando a X (hacemos cada input mayusucula)"""

cosas_copy_upper = [x.upper() for x in cosas]
print(cosas_copy_upper)

"""y ahora list comprehension con condiciones **"if"**"""

cosas_copy_upper_v2 = [x.upper() for x in cosas if len(x) > 5]
print(cosas_copy_upper_v2)

"""##mas exemplos..."""

numerosRandom = [123 , 1233 , 4123 , 4423, 5324, 9643]
numerosRandomCambio = [x**2 for x in numerosRandom]
print(numerosRandomCambio)

listz = [22, 13, 45, 50, 98, 69, 43, 44, 1]
[x+1 if x >= 45 else x+5 for x in listz]

